//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLII_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int employeeId { get; set; }
        public string fullname { get; set; }
        public string IdentityCardNumber { get; set; }
        public string jmbg { get; set; }
        public string phone { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public Nullable<int> managerId { get; set; }
        public Nullable<int> locationId { get; set; }
        public Nullable<int> genderId { get; set; }
        public Nullable<int> sectorId { get; set; }
    
        public virtual tblGender tblGender { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblSector tblSector { get; set; }
    }
}
