//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLII_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public int employeeId { get; set; }
        public string fullname { get; set; }
        public string IdentityCardNumber { get; set; }
        public string jmbg { get; set; }
        public string genderName { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string location { get; set; }
        public string sectorName { get; set; }
        public string manager { get; set; }
        public string phone { get; set; }

        //not mapping properties
        public tblLocation getTblLocation { get; set; }
        public tblEmployee getTblManager { get; set; }
        public tblGender getTblGender { get; set; }

    }
}
